version: "2.2"
services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
  back:
    image: vladshatilov/flask_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.py:/code/config.py
  migrations:
    image: vladshatilov/flask_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c
      "flask db migrate -m 'test' && flask db upgrade"
