version: "3.9"
services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - .\postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db1
  back:
    image: vladshatilov/flask_app:ver-1
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .\config.py:/code/config.py
  migrations:
    image: vladshatilov/flask_app:ver-1
    depends_on:
      postgres:
        condition: service_healthy
    command:
      flask db migrate -m "test" && flask db upgrade
