name: learn-git-actions
on: [push]
jobs:
  build_image_of_the_latest_push:
    runs-on: ubuntu-latest
    steps:
      - name: show dir
        run: ls -l
      - name: clone code
        uses: actions/checkout@v2
      - name: show dir after clone
        run: ls -l
      - name: docker build
        run: docker build -t vladshatilov/flask_app:$GITHUB_REF_NAME_$GITHUB_RUN_ID
      - name: docker login
        run: echo ${{secrets.DOCKER_HUB_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB_USER}} --password-stdin
      - name: docker push
        run: docker push vladshatilov/flask_app:$GITHUB_REF_NAME_$GITHUB_RUN_ID
