name: learn-git-actions
on: [push]
jobs:
  build_image_of_the_latest_push:
    runs-on: ubuntu-latest
    steps:
      - name: show dir
      - run: ls -l
      - name: clone code
      - uses: actions/checkout@v2
      - name: show dir after clone
      - run: ls -l
